### ISSUE TITLE
Error building the Docker image

### ISSUE THREAD

**Issue by X-Ryl669** [ObooSmartClock/Oboo-Source#3] opened 2019-12-20 12:43 UTC
While running the build step in a newly installed VM, got this output:
```
 ---> Running in 5203e96da32f
do_known_hosts: hostkeys_foreach failed: No such file or directory
> Starting build
build.sh: 7: build.sh: cannot create /root/.ssh/known_hosts: Directory nonexistent
Preparing package feeds...
Updating feed 'packages' from 'https://git.lede-project.org/feed/packages.git;lede-17.01' ...
Cloning into './feeds/packages'...
warning: redirecting to https://git.openwrt.org/feed/packages.git/
Create index file './feeds/packages.index'
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..HEAD
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..4242647e96b243bb57610834a7797c2c0455a982
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..HEAD
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..4242647e96b243bb57610834a7797c2c0455a982
Checking 'working-make'... ok.
Checking 'case-sensitive-fs'... ok.
Checking 'proper-umask'... ok.
Checking 'gcc'... ok.
Checking 'working-gcc'... ok.
Checking 'g++'... ok.
Checking 'working-g++'... ok.
Checking 'ncurses'... ok.
Checking 'zlib'... ok.
Checking 'perl-thread-queue'... ok.
Checking 'tar'... ok.
Checking 'find'... ok.
Checking 'bash'... ok.
Checking 'patch'... ok.
Checking 'diff'... ok.
Checking 'cp'... ok.
Checking 'seq'... ok.
Checking 'awk'... ok.
Checking 'grep'... ok.
Checking 'getopt'... ok.
Checking 'stat'... ok.
Checking 'unzip'... ok.
Checking 'bzip2'... ok.
Checking 'wget'... ok.
Checking 'perl'... ok.
Checking 'python'... ok.
Checking 'git'... ok.
Checking 'file'... ok.
Checking 'ldconfig-stub'... ok.
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..HEAD
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..4242647e96b243bb57610834a7797c2c0455a982
Collecting package info: done
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..HEAD
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..4242647e96b243bb57610834a7797c2c0455a982
Collecting target info: done
Updating feed 'luci' from 'https://git.lede-project.org/project/luci.git;lede-17.01' ...
Cloning into './feeds/luci'...
warning: redirecting to https://git.openwrt.org/project/luci.git/
Create index file './feeds/luci.index'
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..HEAD
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..4242647e96b243bb57610834a7797c2c0455a982
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..HEAD
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..4242647e96b243bb57610834a7797c2c0455a982
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..HEAD
    fprintf(stderr, _("\n*** Error during writing of the configuration.\n\n"));
    ^~~~~~~
make[2]: Leaving directory '/root/source/scripts/config'
make[2]: Entering directory '/root/source'
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..HEAD
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..4242647e96b243bb57610834a7797c2c0455a982
make[3]: Entering directory '/root/source/scripts/config'
make[3]: Leaving directory '/root/source/scripts/config'
make[3]: Entering directory '/root/source'
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..HEAD
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..4242647e96b243bb57610834a7797c2c0455a982
make[3]: Leaving directory '/root/source'
tmp/.config-package.in:33796:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:33796:   symbol PACKAGE_luci-lib-nixio is selected by PACKAGE_luci-app-splash
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:33253:   symbol PACKAGE_luci-app-splash is selected by PACKAGE_luci-mod-freifunk-community
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:32317:   symbol PACKAGE_luci-mod-freifunk-community depends on PACKAGE_libuci
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:31090:   symbol PACKAGE_libuci is selected by PACKAGE_rpcd
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:851:     symbol PACKAGE_rpcd is selected by PACKAGE_onion-console-base
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:77017:   symbol PACKAGE_onion-console-base is selected by PACKAGE_onion-console-terminal
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:77059:   symbol PACKAGE_onion-console-terminal depends on PACKAGE_zlib
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:32068:   symbol PACKAGE_zlib is selected by PACKAGE_libopenssl
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:24858:   symbol PACKAGE_libopenssl is selected by PACKAGE_luci-lib-nixio
Error opening terminal: unknown.
/root/source/include/toplevel.mk:127: recipe for target 'menuconfig' failed
make[2]: Leaving directory '/root/source'
make[2]: *** [menuconfig] Error 1
make[1]: *** [.config] Error 2
/root/source/include/toplevel.mk:94: recipe for target '.config' failed
make: *** [world] Error 2
/root/source/include/toplevel.mk:198: recipe for target 'world' failed
```

**Comment by X-Ryl669** [comment] 2019-12-20 20:48
If I use docker to run into the image interactively, then I do get a terminal defined and make menuconfig is run (ugly, but it's run).
It builds, but fails later on.

I tried to copy the ipk for gdbserver and install it (as stated in the README.md) and then I realized the `.config` you've not committed is made for a bigendian system, while the clock is running a little endian system 
Thus the clock is expecting:
```
cat /etc/openwrt_release
DISTRIB_ID='LEDE'
DISTRIB_RELEASE='17.01-SNAPSHOT'
DISTRIB_REVISION='r3517-1b15806'
DISTRIB_CODENAME='reboot'
DISTRIB_TARGET='ramips/mt7688'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='LEDE Reboot 17.01-SNAPSHOT r3517-1b15806'
DISTRIB_TAINTS='no-all busybox'
```
But what is being build by default with this system is: `mips_24kc` (so big endian by default).
```
# grep -i "MIPS" .config
# CONFIG_TARGET_ramips is not set
CONFIG_TARGET_ARCH_PACKAGES="mips_24kc"
CONFIG_DEFAULT_TARGET_OPTIMIZATION="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc"
CONFIG_HAS_MIPS16=y
CONFIG_mips=y
CONFIG_ARCH="mips"
CONFIG_TARGET_OPTIMIZATION="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc"
CONFIG_USE_MIPS16=y
```

**Comment by X-Ryl669** [comment] 2019-12-20 22:13
After tweaking it for a lot of hours, one **must** select these options in the menu config (absolutely non obvious):  Target type as "MediaTek RALINK MIPS" (and not Atheros MT76xx as selected by default) then in the device, one **must** select "RT7688 based board" and then "Oboo smart clock" as the profile).

**Comment by greenbreakfast** [comment] 2019-12-20 23:59
Check the [build.sh](https://github.com/ObooSmartClock/Oboo-Source/blob/master/build.sh) script to see the steps required to build properly for Oboo Smart Clock.

One of the keys is the line `git checkout .config` that restores the config file that's in this repo. While the feeds are being configured in the previous step, the config file will be overwritten. The git checkout command restores the configuration that's for Oboo Smart Clock

**Comment by X-Ryl669** [comment] 2019-12-21 07:26
There's no `.config` in this repo (maybe ignored ?) so currently it's trial and error.

**Comment by greenbreakfast** [comment] 2019-12-22 19:25
Our mistake! Looks like the config file wasn't added in for the initial commit.
It's in the repo now: https://github.com/ObooSmartClock/Oboo-Source/blob/master/.config

**Comment by jravetch** [comment] 2020-01-11 17:59
@X-Ryl669 @greenbreakfast I can confirm building via docker works correctly now, can we please close this issue?

**Comment by greenbreakfast** [comment] 2020-01-17 21:33
Closing issue.

**Closed as completed by greenbreakfast** 2020-01-17 21:33 UTC
